"""First Migrate

Revision ID: 13d28752883e
Revises: 
Create Date: 2020-12-05 14:11:28.128966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d28752883e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('pdf_file', sa.Text(), nullable=True),
    sa.Column('images_file', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ref', sa.String(length=400), nullable=True),
    sa.Column('type_user', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pessoa_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa_projeto')
    op.drop_table('users')
    op.drop_table('projetos')
    # ### end Alembic commands ###
